from typing import List
from pydantic import BaseModel, Field, field_validator
from schemas.common import BaseResponse


class MCQQuestion(BaseModel):
    """
    Represents a single, production-grade Multiple Choice Question generated
    exclusively from the context of the uploaded textbook or document.
    """
    id: int = Field(..., description="Unique incremental identifier for the quiz item (1 to 5).")
    question: str = Field(..., description="The clear, objective question stem generated by the assessor agent.")
    options: List[str] = Field(
        ..., 
        description="A strict array of exactly four distinct logical options or answer choices."
    )
    correct_option_index: int = Field(
        ..., 
        description="The zero-based index pointing directly to the true correct answer within the options array (0, 1, 2, or 3)."
    )
    explanation: str = Field(
        ..., 
        description="Comprehensive pedagogical reasoning explaining why the selected option is correct and why others are incorrect."
    )

    @field_validator("options")
    @classmethod
    def validate_options_count(cls, v: List[str]) -> List[str]:
        """Ensures every single generated question provides exactly 4 choices to fit standard UX layouts."""
        if len(v) != 4:
            raise ValueError(f"An MCQ item must possess exactly 4 distinct options. Found: {len(v)}")
        return v

    @field_validator("correct_option_index")
    @classmethod
    def validate_index_bounds(cls, v: int) -> int:
        """Guarantees the correct answer index points to a valid option array offset."""
        if v < 0 or v > 3:
            raise ValueError(f"Correct option index must map strictly between 0 and 3. Found: {v}")
        return v


class QuizDataPayload(BaseModel):
    """Container holding the rigid list of 5 generated multiple choice questions."""
    questions: List[MCQQuestion] = Field(..., description="Array containing exactly 5 structured assessment items.")

    @field_validator("questions")
    @classmethod
    def validate_quiz_length(cls, v: List[MCQQuestion]) -> List[MCQQuestion]:
        """Enforces the strict requirements-driven threshold of exactly 5 generated questions."""
        if len(v) != 5:
            raise ValueError(f"The production specification requires exactly 5 generated quiz questions. Found: {len(v)}")
        return v


class QuizResponse(BaseResponse):
    """Unified response envelope wrapping the generated automated conceptual evaluation quiz."""
    data: QuizDataPayload = Field(..., description="The actual core quiz structure package.")

    model_config = {
        "json_schema_extra": {
            "example": {
                "success": True,
                "message": "Production assessment quiz containing exactly 5 items compiled successfully.",
                "timestamp": "2026-07-03T20:47:00.000Z",
                "data": {
                    "questions": [
                        {
                            "id": 1,
                            "question": "What is the primary condition causing a state vector to fail normalization?",
                            "options": [
                                "Operating outside a bounded Hilbert Space",
                                "Having an inner product with itself not equal to unity",
                                "Sustaining external multi-agent interference",
                                "Transitioning through a classic SQLite locking phase"
                            ],
                            "correct_option_index": 1,
                            "explanation": "By definition, a state vector is normalized if and only if its inner product with itself equals 1 (unity). If it differs, normalization conditions fail."
                        }
                    ]
                },
                "metadata": {"source_document_chunks": 18}
            }
        }
    }